# Generated by Django 5.2.5 on 2025-08-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mentor_photos/')),
                ('expertise', models.CharField(max_length=200)),
                ('years_experience', models.IntegerField()),
                ('short_bio', models.TextField()),
                ('key_focus_areas', models.TextField()),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('industry', models.CharField(max_length=100)),
                ('business_stage_expertise', models.CharField(choices=[('idea', 'Idea Stage'), ('startup', 'Startup Stage'), ('growth', 'Growth Stage'), ('established', 'Established Business')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mentors',
                'ordering': ['-created_at'],
            },
        ),
    ]
