# Generated by Django 5.2.5 on 2025-08-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mentor',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
