# Generated by Django 5.2.5 on 2025-08-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mentee',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentee',
            name='preferred_meeting_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mentee',
            name='revenue_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mentee',
            name='team_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='years_in_business',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
